
version: '3.9'
services:
  api:
    container_name: game-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    command: [ "/app/main", "runserver"]
    
